version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: apotek-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: apotek-db
      MYSQL_USER: apotekDbUser
      MYSQL_PASSWORD: apotekDbPass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - apotek-network

volumes:
  mysql_data:

networks:
  apotek-network:
    driver: bridge
